#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=03:00:00

set -x
set -e

# Run mrtrix3_mrcat using singularity.
time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./mrtrix3_mrcat.sh

# Check for output.
#[ ! -s dwi.nii ] && exit 1
